import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'New Horizon',
          'login_screen': 'Login Screen ',
          'home_screen': 'Home Screen ',
          'login': 'Login',
          'signup': 'Signup',
          'welcome_back': 'Welcome\nBack',
          'login_successfully': 'Login Successfully',
          'error': 'Error',
          'email': 'Email',
          'email_hint': 'Enter email',
          'password': 'Password',
          'password_hint': 'Enter password',
          'splash_screen': 'Splash Screen',
          'internet_exception':
              "We're unable to show results.\nPlease check your data\nconnection",
          'general_exception':
              "We're unable to unable to process your request.\nPlease try again",
          'retry': 'Retry',
          'error_while_communicating_with_server':
              'Error while communicating with server',
          'no_internet': 'No Internet',
          'request_time_out': 'Request Time Out',
          'internal_server_error': 'Internal server error',
          'invalid_url': 'Invalid Url',
          'error_while_communication': 'Error while communication',
          'failed_to_load_cart': 'Failed to load Cart',
          'failed_to_load_products': 'Failed to load Products',
          'no_products_available': 'No products available',
          'failed_to_fetch_cart_list': 'Failed to fetch cart list',
          'failed_to_fetch_product_list': 'Failed to fetch product list',
          'images': 'Images',
          'no_image_selected': 'No Image Selected',
          'selected_for': 'Selected for ',
          'please_select_jpg_jpeg_png_images_format_only':
              'Please Select jpg & jpeg & png images format only',
          'your_personal_medical_assistant_welcomes_you':
              'Your Personal Medical Assistant Welcomes You!',
          'detail_splash_two':
              'Lorem ipsum dolor sit amet consectur. Morbi errwf e lorem inter er, errwf fermentum nunc naon vitae lorem inter er, rheoncus. Faucibus egestas amet blandit vopat!',
          'try_it_now': 'Try It Now',
          'already_have_an_account': 'Already Have An Account?',
          'slash_login': '  /  Login',
          'remember_me': 'Remember me',
          'forgot_password': 'Forgot Password?',
          'create_a_new_account': 'Create a new Account?',
          'slash_register': '  /  Register',
          'email_not_valid': 'Email not Valid',
          'password_format_invalid': 'Password format Invalid',
          'sign_up': 'Sign Up',
          'full_name': 'Full Name',
          'full_name_hint': 'Enter Full Name',
          'company_name': 'Company Name',
          'company_name_hint': 'Enter Company Name',
          'create_account': 'Create Account',
          'forget_password': 'Forget Password',
          'send_otp': 'Send OTP',
          'otp_verification': 'OTP Verification',
          'verification': 'Verification',
          'enter_your_otp_code_number': 'Enter your OTP code number',
          "i_did_n't_received_otp": "I didn't received OTP?",
          'slash_resend': '  /  Resend',
          'reset_password': 'Reset Password',
          'reset_code': 'Reset Code',
          'reset_code_not_valid': 'Reset Code Not Valid',
          'user_name': 'abc',
          'user_email': 'd@mailinator.com',
          'your_cart_is_empty': 'Your Cart Is Empty!',
          'account_exists': 'Account Exists',
          'account_created': 'Account Created!',
          'password_reset_successfully': 'Password Reset Successfully',
          'full_name_cannot_be_blank': 'Full Name cannot be blank',
          'company_should_exceed_2_characters':
              'Company should exceed 2 characters',
          'email_already_exists': 'Email Already Exists',
          'email_verification_failed': 'Email Verification Failed',
          'invalid_email': 'INVALID EMAIL',
          'invalid_credentials': 'Invalid Credentials. Retry Again!',
          'add_to_cart': 'ADD TO CART',
          'choose_quantity_to_add_in_cart': 'Choose Quantity to add in Cart',
          'subtotal': 'Subtotal',
          'items': 'Items',
          'check_out': 'Check out',
          'free': 'Free',
          'tax': 'Tax',
          'submit': 'Submit',
          'entry_date': "Entry Date",
          'patient_first_name': "Patient's First Name",
          'patient_last_name': "Patient's Last Name",
          'date_of_birth': 'Date of Birth',
          'date_of_service': 'Date of Service',
          'diagnosis': 'Diagnosis',
          'insurance_policy_number': 'Insurance Policy Number',
          'insurance_primary': 'Insurance Primary',
          'provider': 'Provider',
          'treatment_requested': 'Treatment Requested',
          'select_the_documents_from_gallery':
              'Select the documents from Gallery',
          'png_jpeg_jpg_or_heic': 'PNG,JPEG,JPG or HEIC',
          'attach_here': 'Attach Here',
          'secondary_insurance': 'Secondary Insurance',
          'secondary_policy_no': 'Secondary Policy No.',
          'attach_an_id': 'Attach an Id',
          'insurance_card': 'Insurance Card',
          'referral_and_office_note': 'Referral & Office Note',
          'enter_valid_diagnosed_disease': 'Enter Valid Diagnosed Disease',
          'enter_valid_insurance_policy_number':
              'Enter Valid Insurance Policy Number',
          'enter_valid_insurance_primary': 'Enter Valid Insurance Primary',
          'enter_a_valid_first_name': "Enter a valid First Name",
          'enter_valid_last_name': "Enter Valid Last Name",
          'enter_valid_provider': "Enter Valid Provider",
          'enter_valid_treatment_requested': "Enter Valid Treatment Requested",
          'dashboard': "Dashboard",
          'benefit_verification': "Benefit Verification",
          'favorites': "Favorites",
          'products': "Products",
          'patients': "Patients",
          'history': "History",
          'orders': "Orders",
          'invoices': "Invoices",
          'submitted_documents': "Submitted Documents",
          'chat_with_admin': "Chat with Admin",
          'locator': "Locator",
          'payments': "Payments",
          'delete_account': "Delete Account",
          'logout': "Logout",
          'claims': "Claims",
          'view_more': "View More",
          'cart': "Cart",
          'personal_information': "Personal Information",
          'shipping': "Shipping",
          'failed_to_delete_item': "Failed to delete item",
          'failed_to_load_favorites': "Failed to load Favorites",
          'no_favorites_available': "No favorites available",
          'failed_to_fetch_favorites_list': "Failed to fetch favorites list",
          'all_patients': "All Patients",
          'verified': "Verified",
          'pending': "Pending",
          'rejected': "Rejected",
          'failed_to_fetch_patients_list': "Failed to fetch patients list",
          'no_patients_available': "No patients available",
          'are_you_sure_you_want_to_delete': "Are you sure you want to Delete?",
          'failed_to_load_invoices': "Failed to load invoices",
          'failed_to_fetch_invoices_list': "Failed to fetch invoices list",
          'failed_to_load_orders': "Failed to fetch load orders",
          'failed_to_fetch_order_list': "Failed to fetch order list",
          'failed_to_load_verified_patient': "Failed to load verified patient",
          'failed_to_fetch_verified_patient_list':
              "Failed to fetch verified patient list",
          'email_me_with_news_and_offers': 'Email Me With News And Offers',
          'shipping_address': 'Shipping Address',
          'save_this_information_for_next_time':
              'Save This Information For Next Time',
          'use_billing_address_same_as_shipping_address':
              'Use Billing Address Same As Shipping Address',
          'registered_patients': 'Registered Patients',
          'country_region': 'Country / Region',
          'enter_date': 'Enter Date',
          'city': 'City',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'enter_valid_phone': 'Enter valid phone',
          'phone': 'Phone',
          'enter_valid_postal_code': 'Enter valid postal code',
          'postal_code': 'Postal Code',
          'schedule_delivery': 'Schedule Delivery',
          'enter_valid_address': 'Enter valid address',
          'address': 'Address',
          'failed_to_load_documents': 'Failed to load documents',
          'failed_to_fetch_documents_list': 'Failed to fetch documents list',
          'documents': 'Documents',
          'user_docs': 'User Docs',
          'admin_docs': 'Admin Docs',
          'upload': 'Upload',
          'file_upload': 'File Upload',
          'upload_document': 'Upload Document',
          'failed_to_load_notification': 'Failed to load notification',
          'failed_to_fetch_notification_list':
              'Failed to fetch notification list',
          'notifications': 'Notifications',
          'no_notification_found': 'No Notifications Found',
          'failed_to_load_chats': 'Failed to load chats',
          'failed_to_fetch_chat_list': 'Failed to fetch chat list',
          'nhm_admin': 'NHM Admin',
          'online': 'online',
          'failed_to_load_doctors': 'Failed to load doctors',
          'failed_to_fetch_doctors_list': 'Failed to fetch doctors list',
          'type_a_message': 'Type a Message',
        },
        'ur_PK': {
          'email_hint': 'ای میل درج کریں',
          'splash_screen': 'سپلیش اسکرین',
        },
      };
}
